### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by AlloVince** [AlloVince/avnpc.front#2]
- [x] RSS
- [x] Search
- [x] Better Menu highlighter
- [x] Number font issue
- [x] Better Error page
- [x] Docker-compose
- [x] universal config
- [x] Tag filter
- [x] debug mode switch
- [x] Donate
- [ ] Analytics
- [ ] Markdown content convert
- [ ] Evernote images
- [ ] Production optimize
- [ ] View caches
- [x] Webpack optimize (css as an external file)
- [ ] *CDN
- [ ] *TOC
- [ ] *SEO
- [x] *Loading
- [ ] *Logger
- [ ] *Mobile device
- [ ] *Sitemap
